workflows:
  ios-native-workflow:
    name: iOS Auto Build & Upload
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: SabihKey

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.levelUpSport
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        INFO_PLIST_PATH: "ios/Runner/Info.plist"
        BUNDLE_ID: "com.example.levelUpSport"

    scripts:
      - name: 🧹 Clean Flutter and iOS folders
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get

      - name: 🍎 Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: 🔢 Update Info.plist version safely
        script: |
          INFO_PLIST=$INFO_PLIST_PATH
          if [ ! -f "$INFO_PLIST" ]; then
            echo "❌ Info.plist not found at $INFO_PLIST"
            exit 1
          fi

          CURRENT_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$INFO_PLIST" || echo "1.0.0")
          CURRENT_BUILD=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$INFO_PLIST" || echo "0")

          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_PATCH=$((patch + 1))
          NEW_VERSION="${major}.${minor}.${NEW_PATCH}"
          NEW_BUILD=$((CURRENT_BUILD + 1))

          echo "🔧 Updating Info.plist → Version: $NEW_VERSION | Build: $NEW_BUILD"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_VERSION" "$INFO_PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$INFO_PLIST"

      - name: 🧾 Use provisioning profiles
        script: |
          xcode-project use-profiles --project ios/Runner.xcodeproj

      - name: 🏗️ Build IPA for App Store Connect
        script: |
          echo "🚀 Building IPA..."
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
          echo "✅ IPA build completed."

      - name: 🩹 Fix Info.plist inside built IPA before upload
        script: |
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA found for upload!"
            exit 1
          fi

          echo "🔧 Patching Info.plist inside $IPA_PATH ..."
          mkdir -p extracted_ipa
          unzip -q "$IPA_PATH" -d extracted_ipa

          APP_PLIST=$(find extracted_ipa/Payload -name "Info.plist" | head -1)
          if [ ! -f "$APP_PLIST" ]; then
            echo "❌ Info.plist not found in archive!"
            exit 1
          fi

          # Ensure both keys exist
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string 1" "$APP_PLIST" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 1.0.0" "$APP_PLIST" 2>/dev/null || true

          # Copy values from source Info.plist
          SRC_PLIST=$INFO_PLIST_PATH
          SRC_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$SRC_PLIST")
          SRC_BUILD=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$SRC_PLIST")

          echo "Setting archive Info.plist to Version=$SRC_VERSION Build=$SRC_BUILD"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $SRC_VERSION" "$APP_PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $SRC_BUILD" "$APP_PLIST"

          # Re-zip the IPA
          cd extracted_ipa
          zip -qry "../fixed.ipa" .
          cd ..
          mv fixed.ipa "$IPA_PATH"
          echo "✅ Fixed Info.plist inside archive."

      - name: 🚀 Upload to App Store Connect (TestFlight)
        script: |
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          echo "📤 Uploading $IPA_PATH to App Store Connect..."
          app-store-connect upload \
            --path "$IPA_PATH" \
            --use-latest-version \
            --submit-for-testflight true || {
              echo "⚠️ Upload failed, retrying in 30s..."
              sleep 30
              app-store-connect upload \
                --path "$IPA_PATH" \
                --use-latest-version \
                --submit-for-testflight true
            }
          echo "✅ Upload complete! Check App Store Connect → TestFlight."

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - levelupsports96@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
