workflows:
  ios-auto-testflight:
    name: iOS Auto Build & Upload to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: SabihKey

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.levelUpSport
      xcode: latest
      cocoapods: default
      vars:
        INFO_PLIST_PATH: "ios/Runner/Info.plist"
        BUNDLE_ID: "com.example.levelUpSport"
        APP_STORE_CONNECT_TEAM_ID: $APP_STORE_CONNECT_TEAM_ID

    scripts:
      - name: 🧹 Clean & install dependencies
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get
          cd ios && pod install && cd ..

      - name: 🔢 Auto increment version & build number
        script: |
          INFO_PLIST=$INFO_PLIST_PATH
          CURRENT_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$INFO_PLIST" || echo "1.0.0")
          CURRENT_BUILD=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$INFO_PLIST" || echo "0")

          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_PATCH=$((patch + 1))
          NEW_VERSION="${major}.${minor}.${NEW_PATCH}"
          NEW_BUILD=$((CURRENT_BUILD + 1))

          echo "🔧 Updating Info.plist → Version: $NEW_VERSION | Build: $NEW_BUILD"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_VERSION" "$INFO_PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$INFO_PLIST"
          echo "✅ Updated to Version=$NEW_VERSION Build=$NEW_BUILD"

      - name: 🏗️ Build and export IPA
        script: |
          echo "🚀 Building Flutter IPA..."
          flutter build ipa --release || {
            echo "❌ Flutter build failed!"
            exit 1
          }

          echo "📦 Searching for archive..."
          ARCHIVE_PATH=$(find build/ios/archive -name "*.xcarchive" | head -1)
          if [ -z "$ARCHIVE_PATH" ]; then
            echo "⚠️ No .xcarchive found, trying to locate existing IPA..."
            IPA_PATH=$(find build/ios -name "*.ipa" | head -1)
          else
            echo "📦 Found archive: $ARCHIVE_PATH"
            mkdir -p build/ios/ipa
            echo "📤 Exporting IPA from archive..."
            cat > exportOptions.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key><string>app-store</string>
  <key>uploadBitcode</key><false/>
  <key>uploadSymbols</key><true/>
  <key>signingStyle</key><string>manual</string>
  <key>stripSwiftSymbols</key><true/>
  <key>teamID</key><string>${APP_STORE_CONNECT_TEAM_ID}</string>
</dict>
</plist>
EOF

            xcodebuild -exportArchive \
              -archivePath "$ARCHIVE_PATH" \
              -exportPath build/ios/ipa \
              -exportOptionsPlist exportOptions.plist \
              -allowProvisioningUpdates
          fi

          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ IPA export failed. Please check logs."
            exit 1
          fi
          echo "✅ IPA ready at: $IPA_PATH"

      - name: 🚀 Upload to TestFlight
        script: |
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA found to upload!"
            exit 1
          fi
          echo "📤 Uploading $IPA_PATH to TestFlight..."
          app-store-connect upload \
            --path "$IPA_PATH" \
            --use-latest-version \
            --submit-for-testflight true \
            --groups "LevelUpSports"
          echo "✅ Upload complete!"

    artifacts:
      - build/ios/**/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - levelupsports96@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
