workflows:
  ios-auto-upload:
    name: iOS Auto Build & Upload
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: SabihKey

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      groups:
        - app_store_connect
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.levelUpSport
      xcode: latest
      cocoapods: default
      vars:
        INFO_PLIST_PATH: "ios/Runner/Info.plist"
        BUNDLE_ID: "com.example.levelUpSport"
        APP_STORE_CONNECT_TEAM_ID: $APP_STORE_CONNECT_TEAM_ID

    scripts:
      - name: 🧹 Clean & install dependencies
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get
          cd ios && pod install && cd ..

      - name: 🔢 Auto increment version & build number
        script: |
          INFO_PLIST=$INFO_PLIST_PATH

          CURRENT_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$INFO_PLIST" || echo "1.0.0")
          CURRENT_BUILD=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$INFO_PLIST" || echo "0")

          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_PATCH=$((patch + 1))
          NEW_VERSION="${major}.${minor}.${NEW_PATCH}"
          NEW_BUILD=$((CURRENT_BUILD + 1))

          echo "🔧 Updating Info.plist → Version=$NEW_VERSION Build=$NEW_BUILD"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_VERSION" "$INFO_PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$INFO_PLIST"

      - name: 🏗️ Build iOS IPA for App Store
        script: |
          echo "🚀 Building iOS archive..."
          mkdir -p build/ios/archive
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/ios/archive/Runner.xcarchive \
            DEVELOPMENT_TEAM="$APP_STORE_CONNECT_TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            clean archive CODE_SIGN_STYLE=Automatic | xcpretty

          echo "📦 Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist <(cat <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store-connect</string>
            <key>teamID</key><string>$APP_STORE_CONNECT_TEAM_ID</string>
            <key>signingStyle</key><string>automatic</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF
          ) \
            -exportPath build/ios/ipa | xcpretty

      - name: 🚀 Upload to App Store Connect (TestFlight)
        script: |
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA found!"
            exit 1
          fi
          echo "📤 Uploading $IPA_PATH to App Store Connect..."
          app-store-connect upload \
            --path "$IPA_PATH" \
            --use-latest-version \
            --submit-for-testflight true
          echo "✅ Upload complete! Check TestFlight for new build."

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - levelupsports96@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
