workflows:
  ios-native-workflow:
    name: iOS App Store Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: SabihKey   # ✅ your Codemagic Apple API integration key

    environment:
      groups:
        - app_store_connect          # ✅ this links to the environment variable group you set
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.levelUpSport
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.levelUpSport"
        APP_STORE_APPLE_ID: 6754937234  # your app's Apple ID

    scripts:
      - name: Clean Flutter and iOS folders
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Use provisioning profiles
        script: |
          xcode-project use-profiles --project ios/Runner.xcodeproj

      - name: Build IPA for App Store
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - levelupsports96@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
