workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: SabihKey
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.levelUpSport
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.levelUpSport"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_APPLE_ID: 6754937234

    scripts:
      - name: Clean Flutter and iOS build folders
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Set up provisioning profiles for iOS project only
        script: |
          xcode-project use-profiles --project ios/Runner.xcodeproj

      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store \
            --team-id B6Z4CUVQVP

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - levelupsports96@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
