// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_j-VVRFSQzV3Tgancf9Jco9Hs64_oPQk',
    appId: '1:779252114785:web:e0b32206e8a132279c1120',
    messagingSenderId: '779252114785',
    projectId: 'levelupsports-1014f',
    authDomain: 'levelupsports-1014f.firebaseapp.com',
    storageBucket: 'levelupsports-1014f.firebasestorage.app',
    measurementId: 'G-BLEJ0NJL6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEudAwgmSYq6wsOyRCeqSSr53nRfsHEeo',
    appId: '1:779252114785:android:873e66ac2596da4d9c1120',
    messagingSenderId: '779252114785',
    projectId: 'levelupsports-1014f',
    storageBucket: 'levelupsports-1014f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyGkWjIrVHjCFEovUE8T5WuPxC20N_Ao',
    appId: '1:779252114785:ios:a0f793440a748ea59c1120',
    messagingSenderId: '779252114785',
    projectId: 'levelupsports-1014f',
    storageBucket: 'levelupsports-1014f.firebasestorage.app',
    iosBundleId: 'com.example.levelUpSport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFyGkWjIrVHjCFEovUE8T5WuPxC20N_Ao',
    appId: '1:779252114785:ios:dcb9338c5e07a66b9c1120',
    messagingSenderId: '779252114785',
    projectId: 'levelupsports-1014f',
    storageBucket: 'levelupsports-1014f.firebasestorage.app',
    iosBundleId: 'com.example.levelUpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_j-VVRFSQzV3Tgancf9Jco9Hs64_oPQk',
    appId: '1:779252114785:web:fe4746a7b35aee1d9c1120',
    messagingSenderId: '779252114785',
    projectId: 'levelupsports-1014f',
    authDomain: 'levelupsports-1014f.firebaseapp.com',
    storageBucket: 'levelupsports-1014f.firebasestorage.app',
    measurementId: 'G-P2LCG36CSM',
  );
}
